services:
  bitcoin:
    image: bitcoin/bitcoin:latest
    container_name: bitcoin-mainnet
    restart: unless-stopped
    ports:
      - "8332:8332"  # RPC
      - "8333:8333"  # P2P
    volumes:
      - /media/honey/bitcoin_data/bitcoin-node:/home/bitcoin/.bitcoin
    # This commands are now in the /mnt/bitcoin-data/bitcoin.conf file
    # command:
    #   -printtoconsole
    #   -rpcallowip=0.0.0.0/0
    #   -rpcbind=0.0.0.0
    #   -rpcuser=bitcoin
    #   -rpcpassword=bitcoin123
    #   -txindex=1

  explorador_api:
    build:
      context: ./explorador_sigiloso_api
    container_name: explorador-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      BTC_RPC_URL: http://bitcoin:8332
      BTC_RPC_USER: bitcoin
      BTC_RPC_PASS: bitcoin123
    command: ["cargo", "run", "--release"]

  # Esplora indexer (backend)
  esplora-indexer:
    image: blockstream/esplora:latest
    container_name: esplora-indexer
    restart: unless-stopped
    depends_on:
      - bitcoin
    environment:
      - NETWORK=bitcoin-mainnet
      - BITCOIN_RPC_URL=http://bitcoin:8332
      - BITCOIN_RPC_USER=bitcoin
      - BITCOIN_RPC_PASS=bitcoin123
      - DB_DIR=/data
      - RUST_LOG=info                 # optional: more verbose logs
      - DEBUG=verbose                 # optional: more verbose logs
    volumes:
      - /media/honey/bitcoin_data/esplora-db:/data
    command:
      - bash
      - -c
      - >
        /srv/explorer/electrs_bitcoin/bin/electrs
        --network bitcoin
        --daemon-rpc-addr=bitcoin:8332
        --cookie=bitcoin:bitcoin123
        --http-addr=0.0.0.0:3000
        --monitoring-addr=0.0.0.0:4224
        --electrum-rpc-addr=0.0.0.0:50001
        --db-dir=/data/electrs_bitcoin_db/mainnet
    ports:
      - "3000:3000"   # HTTP API
      # - "8080:80"        # HTTP UI + API