[package]
name = "explorador_sigiloso_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bitcoincore-rpc = "0.19.0"
bitcoin = "0.32.5"

